name: Insomani
favicon: null
layout_spectrum: 0.25466
typography_spectrum: 0.25799
title: Insomani
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1a1a1a'
    - '#3598dc'
    - '#545454'
    - '#8bc1e6'
  brandStrength: 0.125
  lightness: 0.0625
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
